version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181
    volumes:
      - ./zookeeper_data:/data
  kafka:
    build: .
    ports:
      - 9092:9092
    environment:
      DOCKER_API_VERSION: 1.22
      KAFKA_ADVERTISED_HOST_NAME: 192.168.1.108
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "topic1:1:1,topic2:3:1,topicName:1:1"
    volumes:
      - ./volume:/var/run/docker.sock
